name: update
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4.2.0
    - uses: cachix/install-nix-action@v29
    - name: update
      run: |
        nix flake update
    - name: build
      run: |
        nix eval --raw .#nixosConfigurations.nixos.config.system.build.toplevel
    - uses: stefanzweifel/git-auto-commit-action@v5.0.1
